GET http://localhost:8000/api/staff/logout
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjcyNjY0LCJpYXQiOjE3MDUyNzI2MDQsImp0aSI6ImJlOTgzZWJmZDg3MTRlNzc5NzYyMzNjMGZjMTkwYmRmIiwidXNlcl9pZCI6MX0.aIu059KM35KcaJbT_0bgvcxDln5VO6iwFPlqy5A_jeA

###

GET http://localhost:8000/api/staff/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjcyNzQwLCJpYXQiOjE3MDUyNzI2ODAsImp0aSI6Ijg5NjQzZTBkMmU1MjRkYWE4ZjJkYWMxYTUxMGFmNzViIiwidXNlcl9pZCI6MX0.IggJ6IM9UtY3V-V7Otx5rRrvRbPO_iKqaQBZudIMVfo

###

POST http://localhost:8000/api/staff/obtain-pair
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}
###

POST http://localhost:8000/api/staff/verify-token
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjcyMTE3LCJpYXQiOjE3MDUyNzIwNTcsImp0aSI6Ijk2MGU2NDMxZDcyMjRkODJiNzdjMjE2NjA4NGM5MDE3IiwidXNlcl9pZCI6MX0.Rnqld6YL2fnIjX8UhTBAoW6p4mszVLFezHd-BnovO8Q

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjcyMjIzLCJpYXQiOjE3MDUyNzIxNjMsImp0aSI6ImQ4YWNiZDNhMDEyMTQxZDM5MzFlYjJhNTVjMTMzZmY4IiwidXNlcl9pZCI6MX0.9je8bCzrQ9l7Jbf7Re9hwg423dKYTPbxAOOivVdJINQ"
}
###