# Generated by Django 5.0.1 on 2024-01-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Review',
        ),
    ]
