# Generated by Django 5.0.1 on 2024-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telegram',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
