# Generated by Django 5.0.1 on 2024-01-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_appointment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
